title: "[RFC]: "
labels:
  - rfc
body:
  - type: markdown
    attributes:
      value: |
        RFC (Request for Comments) 用于提出重大技术方案或架构变更。提交后，Claude 将自动评估方案的可行性。

  - type: textarea
    id: summary
    attributes:
      label: 摘要
      description: 用一两句话概述这个提案
      placeholder: 简要描述你的提案...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机
      description: 为什么需要这个变更？解决什么问题？
      placeholder: |
        当前存在什么问题？
        这个提案如何解决这些问题？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 详细设计
      description: 详细描述你的技术方案
      placeholder: |
        ## 架构设计
        描述整体架构...

        ## 接口设计
        描述 API 或接口...

        ## 数据模型
        描述数据结构...

        ## 实现步骤
        1. 第一步...
        2. 第二步...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 你考虑过哪些其他方案？为什么选择当前方案？
      placeholder: |
        ## 方案 A
        描述...
        优点：...
        缺点：...

        ## 方案 B
        ...

  - type: textarea
    id: impact
    attributes:
      label: 影响评估
      description: 这个变更会影响哪些部分？
      placeholder: |
        - 受影响的模块：
        - 需要迁移的数据：
        - 向后兼容性：
        - 性能影响：

  - type: textarea
    id: risks
    attributes:
      label: 风险和缓解措施
      description: 有哪些潜在风险？如何缓解？
      placeholder: |
        | 风险 | 影响 | 缓解措施 |
        |------|------|----------|
        | ... | ... | ... |

  - type: textarea
    id: timeline
    attributes:
      label: 时间线（可选）
      description: 预期的实现时间线
      placeholder: |
        - 阶段1：...
        - 阶段2：...
